# Generated by Django 6.0.1 on 2026-03-13 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_generation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiprompt',
            name='generated_content',
        ),
        migrations.RemoveField(
            model_name='aiprompt',
            name='prompt_type',
        ),
        migrations.CreateModel(
            name='AutomationStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Strategy Name (e.g., Daily Cat Facts)', max_length=100)),
                ('concept_prompt', models.TextField(help_text='The core concept for AI generation')),
                ('platform', models.CharField(choices=[('Instagram', 'Instagram'), ('YouTube', 'YouTube')], max_length=20)),
                ('content_type', models.CharField(choices=[('image', 'Image (DALL-E 3)'), ('video', 'Video (Sora)')], default='image', max_length=10)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=10)),
                ('time_of_day', models.TimeField(help_text='Preferred time to post')),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
