# Generated by Django 6.0.1 on 2026-03-16 14:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_generation', '0002_remove_aiprompt_generated_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationStrategy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Strategy Name (e.g., Daily Cat Facts)', max_length=100)),
                ('concept_prompt', models.TextField(help_text='The core concept for AI generation')),
                ('platform', models.CharField(choices=[('Instagram', 'Instagram'), ('YouTube', 'YouTube')], max_length=20)),
                ('content_type', models.CharField(choices=[('image', 'Image (DALL-E 3)'), ('video', 'Video (Sora)')], default='image', max_length=10)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=10)),
                ('time_of_day', models.TimeField(help_text='Preferred time to post')),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_strategies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Automation Strategy',
                'verbose_name_plural': 'Automation Strategies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='AutomationStrategy',
        ),
    ]
