# Generated by Django 6.0.1 on 2026-03-17 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_generation', '0004_automationstrategy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automationstrategy',
            options={'verbose_name': 'Automation Strategy', 'verbose_name_plural': 'Automation Strategies'},
        ),
        migrations.RemoveField(
            model_name='automationstrategy',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='automationstrategy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
