# Generated by Django 6.0.1 on 2026-03-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_generation', '0005_alter_automationstrategy_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationstrategy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
