# Generated by Django 6.0.1 on 2026-03-20 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_generation', '0006_automationstrategy_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automationstrategy',
            options={'ordering': ['-created_at'], 'verbose_name': 'Automation Strategy', 'verbose_name_plural': 'Automation Strategies'},
        ),
        migrations.AlterField(
            model_name='automationstrategy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_strategies', to=settings.AUTH_USER_MODEL),
        ),
    ]
