# Generated by Django 6.0.1 on 2026-03-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='hashtags',
            field=models.TextField(blank=True, help_text='Generated Hashtags'),
        ),
        migrations.AlterField(
            model_name='content',
            name='description',
            field=models.TextField(blank=True, help_text='Generated Caption'),
        ),
    ]
